# Generated by Django 4.0.6 on 2022-07-11 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('presence', models.BooleanField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
